### ISSUE TITLE
oso_lets_go authentication errors

### ISSUE THREAD

**Issue by ravenac95** [opensource-observer/oso#2215]
### To Reproduce

It seems there is some kind of issue when trying to use oso_lets_go. Unknown reproduction at this time

### Describe the Bug

```
Ensuring Service Usage APIs are enabled to allow service account creation
Service Usage API enabled
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/evanmeyer/Desktop/work/oso/warehouse/oso_lets_go/wizard.py", line 567, in run
    dataset = bq_client.update_dataset(dataset, ["access_entries"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evanmeyer/Desktop/work/oso/oso-data/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 1228, in update_dataset
    api_response = self._call_api(
                   ^^^^^^^^^^^^^^^
  File "/Users/evanmeyer/Desktop/work/oso/oso-data/lib/python3.12/site-packages/google/cloud/bigquery/client.py", line 833, in _call_api
    return call()
           ^^^^^^
  File "/Users/evanmeyer/Desktop/work/oso/oso-data/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/Users/evanmeyer/Desktop/work/oso/oso-data/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 153, in retry_target
    _retry_error_helper(
  File "/Users/evanmeyer/Desktop/work/oso/oso-data/lib/python3.12/site-packages/google/api_core/retry/retry_base.py", line 212, in _retry_error_helper
    raise final_exc from source_exc
  File "/Users/evanmeyer/Desktop/work/oso/oso-data/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/Users/evanmeyer/Desktop/work/oso/oso-data/lib/python3.12/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/oso-data-436717/datasets/oso_production?prettyPrint=false: cannot specify both linked_dataset_source and default_table_expiration_ms 
```

### Expected Behavior

This shouldn't error

**Comment by ccerv1** [comment]
Is this still an issue?

**Comment by ryscheng** [comment]
We are moving away from interacting with Google APIs directly, towards pyoso.
Not necessary anymore
